name: Auto-Merge Exercism PRs

on:
  pull_request:
    types: [opened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PRs from Exercism bot
        uses: pascalgn/automerge-action@v0.15.3
        if: github.actor == 'exercism[bot]'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mergeMethod: squash
