name: Auto-Merge Exercism PRs

# Trigger on new or updated pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge Exercism PRs
        uses: pascalgn/automerge-action@v0.15.3
        # Only trigger on PRs created by any Exercism bot
        if: startsWith(github.actor, 'exercism')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mergeMethod: squash        # You can change to merge or rebase
          commitMessage: title       # Use PR title as commit message
          mergeComment: true         # Leave a comment after merge
          # Optional: continue-on-error avoids workflow failure if merge fails
        continue-on-error: true
